#!/bin/bash
do_waiter=./../waitress

./../sleep_random&
pid1=$!
echo "lunched $pid1, alpha"

./../sleep_random&
pid2=$!
echo "lunched $pid2, beta"

./../sleep_random&
pid3=$!
echo "lunched $pid3, charlie"


$do_waiter $pid1 10 "alpha"
echo "$pid1 finished"
$do_waiter $pid2 10 "beta"
echo "$pid2 finished"
$do_waiter $pid3 10 "charlie"
echo "$pid3 finished"
