#!/bin/bash
set -feo pipefail

#example input : 20150101   yyyymmdd
startDate=${1:?startDate cannot be empty}
endDate=${2:?endDate cannot be empty}
custom_format=${3:-%Y%m%d}

d=$startDate
while [ "$d" != "$endDate" ]; do
  echo $custom_d
  #d=$(date +%Y%m%d -d "$d + 1 day")
  d=$(date +%Y%m%d -d "$d + 1 day")
  custom_d=$(date +${custom_format} -d "$d + 1 day")
done
