#!/bin/bash
#this script will search all directory defined in env var $MY_SOURCE_CODE_DIR and find any code contains the keyword
source common
code=${1:?code_signature empty}
list_file_only=${2:false}
if $list_file_only;then
  search_code_base $MY_SOURCE_CODE_DIR $code
else
  find $MY_SOURCE_CODE_DIR $code
fi
